---
name: ade20k_full
distinct: true
offset: -1
groups:
  - {name: wall, labels: [1]}
  - {name: building, labels: [2]}
  - {name: sky, labels: [3]}
  - {name: floor, labels: [4]}
  - {name: tree, labels: [5]}
  - {name: ceiling, labels: [6]}
  - {name: road, labels: [7]}
  - {name: bed, labels: [8]}
  - {name: windowpane, labels: [9]}
  - {name: grass, labels: [10]}
  - {name: cabinet, labels: [11]}
  - {name: sidewalk, labels: [12]}
  - {name: person, labels: [13]}
  - {name: earth, labels: [14]}
  - {name: door, labels: [15]}
  - {name: table, labels: [16]}
  - {name: mountain, labels: [17]}
  - {name: plant, labels: [18]}
  - {name: curtain, labels: [19]}
  - {name: chair, labels: [20]}
  - {name: car, labels: [21]}
  - {name: water, labels: [22]}
  - {name: painting, labels: [23]}
  - {name: sofa, labels: [24]}
  - {name: shelf, labels: [25]}
  - {name: house, labels: [26]}
  - {name: sea, labels: [27]}
  - {name: mirror, labels: [28]}
  - {name: rug, labels: [29]}
  - {name: field, labels: [30]}
  - {name: armchair, labels: [31]}
  - {name: seat, labels: [32]}
  - {name: fence, labels: [33]}
  - {name: desk, labels: [34]}
  - {name: rock, labels: [35]}
  - {name: wardrobe, labels: [36]}
  - {name: lamp, labels: [37]}
  - {name: bathtub, labels: [38]}
  - {name: railing, labels: [39]}
  - {name: cushion, labels: [40]}
  - {name: base, labels: [41]}
  - {name: box, labels: [42]}
  - {name: column, labels: [43]}
  - {name: signboard, labels: [44]}
  - {name: chest, labels: [45]}
  - {name: counter, labels: [46]}
  - {name: sand, labels: [47]}
  - {name: sink, labels: [48]}
  - {name: skyscraper, labels: [49]}
  - {name: fireplace, labels: [50]}
  - {name: refrigerator, labels: [51]}
  - {name: grandstand, labels: [52]}
  - {name: path, labels: [53]}
  - {name: stairs, labels: [54]}
  - {name: runway, labels: [55]}
  - {name: case, labels: [56]}
  - {name: pool, labels: [57]}
  - {name: pillow, labels: [58]}
  - {name: screen, labels: [59]}
  - {name: stairway, labels: [60]}
  - {name: river, labels: [61]}
  - {name: bridge, labels: [62]}
  - {name: bookcase, labels: [63]}
  - {name: blind, labels: [64]}
  - {name: coffee, labels: [65]}
  - {name: toilet, labels: [66]}
  - {name: flower, labels: [67]}
  - {name: book, labels: [68]}
  - {name: hill, labels: [69]}
  - {name: bench, labels: [70]}
  - {name: countertop, labels: [71]}
  - {name: stove, labels: [72]}
  - {name: palm, labels: [73]}
  - {name: kitchen, labels: [74]}
  - {name: computer, labels: [75]}
  - {name: swivel, labels: [76]}
  - {name: boat, labels: [77]}
  - {name: bar, labels: [78]}
  - {name: arcade, labels: [79]}
  - {name: hovel, labels: [80]}
  - {name: bus, labels: [81]}
  - {name: towel, labels: [82]}
  - {name: light, labels: [83]}
  - {name: truck, labels: [84]}
  - {name: tower, labels: [85]}
  - {name: chandelier, labels: [86]}
  - {name: awning, labels: [87]}
  - {name: streetlight, labels: [88]}
  - {name: booth, labels: [89]}
  - {name: television, labels: [90]}
  - {name: airplane, labels: [91]}
  - {name: dirt, labels: [92]}
  - {name: apparel, labels: [93]}
  - {name: pole, labels: [94]}
  - {name: land, labels: [95]}
  - {name: bannister, labels: [96]}
  - {name: escalator, labels: [97]}
  - {name: ottoman, labels: [98]}
  - {name: bottle, labels: [99]}
  - {name: buffet, labels: [100]}
  - {name: poster, labels: [101]}
  - {name: stage, labels: [102]}
  - {name: van, labels: [103]}
  - {name: ship, labels: [104]}
  - {name: fountain, labels: [105]}
  - {name: conveyer, labels: [106]}
  - {name: canopy, labels: [107]}
  - {name: washer, labels: [108]}
  - {name: plaything, labels: [109]}
  - {name: swimming, labels: [110]}
  - {name: stool, labels: [111]}
  - {name: barrel, labels: [112]}
  - {name: basket, labels: [113]}
  - {name: waterfall, labels: [114]}
  - {name: tent, labels: [115]}
  - {name: bag, labels: [116]}
  - {name: minibike, labels: [117]}
  - {name: cradle, labels: [118]}
  - {name: oven, labels: [119]}
  - {name: ball, labels: [120]}
  - {name: food, labels: [121]}
  - {name: step, labels: [122]}
  - {name: tank, labels: [123]}
  - {name: trade, labels: [124]}
  - {name: microwave, labels: [125]}
  - {name: pot, labels: [126]}
  - {name: animal, labels: [127]}
  - {name: bicycle, labels: [128]}
  - {name: lake, labels: [129]}
  - {name: dishwasher, labels: [130]}
  - {name: screen, labels: [131]}
  - {name: blanket, labels: [132]}
  - {name: sculpture, labels: [133]}
  - {name: hood, labels: [134]}
  - {name: sconce, labels: [135]}
  - {name: vase, labels: [136]}
  - {name: traffic, labels: [137]}
  - {name: tray, labels: [138]}
  - {name: ashcan, labels: [139]}
  - {name: fan, labels: [140]}
  - {name: pier, labels: [141]}
  - {name: crt, labels: [142]}
  - {name: plate, labels: [143]}
  - {name: monitor, labels: [144]}
  - {name: bulletin, labels: [145]}
  - {name: shower, labels: [146]}
  - {name: radiator, labels: [147]}
  - {name: glass, labels: [148]}
  - {name: clock, labels: [149]}
  - {name: flag, labels: [150]}
specified_colors:
  - {name: floor, source: raw, color: [0.75, 0.75, 0.71]}
  - {name: wall, source: raw, color: [0.0, 0.4, 0.2]}
  - {name: ceiling, source: raw, color: [0.8, 0.0, 0.4]}
