---
name: ade20k_indoor
distinct: true
offset: -1
groups:
  - {name: Unknown, labels: [3, 7, 10, 12, 14, 17, 21, 22, 26, 27, 30, 33, 35, 38, 47, 49, 50, 52, 53, 55, 61, 62, 69, 77, 79, 80, 81, 84, 85, 91, 92, 95, 103, 104, 110, 114, 115, 117, 123, 124, 129, 137,
      141]}
  - {name: Wall, labels: [1, 2]}
  - {name: Floor, labels: [4, 29, 102, 106]}
  - {name: Ceiling, labels: [6, 87, 107]}
  - {name: Door, labels: [15, 59]}
  - {name: Stairs, labels: [54, 60, 97, 122]}
  - {name: Structure, labels: [9, 19, 39, 41, 43, 64, 89, 94, 96, 105]}
  - {name: Shelf, labels: [25, 63, 71, 74, 78, 100]}
  - {name: Plant, labels: [5, 18, 67, 73, 126, 136]}
  - {name: Bed, labels: [8, 58, 118]}
  - {name: Storage, labels: [11, 36, 42, 45, 56, 112, 113, 116]}
  - {name: Table, labels: [16, 34, 46, 57, 65]}
  - {name: Chair, labels: [20, 31, 32, 76, 111]}
  - {name: Wall_Decoration, labels: [23, 28, 44, 101, 145, 149, 150]}
  - {name: Couch, labels: [24, 40, 70, 98]}
  - {name: Light, labels: [37, 83, 86, 88, 135, 140]}
  - {name: Appliance, labels: [48, 51, 66, 72, 108, 119, 125, 130, 134, 146, 147]}
  - {name: Thing, labels: [68, 75, 90, 109, 120, 128, 131, 133, 138, 139, 142, 144, 99, 121, 143, 148]}
  - {name: Deformable, labels: [82, 93, 132]}
  - {name: Dynamic_NonHuman, labels: [127]}
  - {name: Human, labels: [13]}
specified_colors:
  - {name: Floor, source: raw, color: [0.75, 0.75, 0.71]}
  - {name: Wall, source: raw, color: [0.0, 0.4, 0.2]}
  - {name: Ceiling, source: raw, color: [0.7, 0.0, 0.7]}
  - {name: Door, source: raw, color: [1.0, 0.7, 0.0]}
  - {name: Couch, source: raw, color: [0.8, 0.0, 0.0]}
  - {name: Table, source: raw, color: [0.8, 0.0, 0.4]}
