---
name: mpcat40
groups:
  - {name: void, labels: [0, 41]}
  - {name: wall, labels: [1]}
  - {name: floor, labels: [2]}
  - {name: chair, labels: [3]}
  - {name: door, labels: [4]}
  - {name: table, labels: [5]}
  - {name: picture, labels: [6]}
  - {name: cabinet, labels: [7]}
  - {name: cushion, labels: [8]}
  - {name: window, labels: [9]}
  - {name: sofa, labels: [10]}
  - {name: bed, labels: [11]}
  - {name: curtain, labels: [12]}
  - {name: chest_of_drawers, labels: [13]}
  - {name: plant, labels: [14]}
  - {name: sink, labels: [15]}
  - {name: stairs, labels: [16]}
  - {name: ceiling, labels: [17]}
  - {name: toilet, labels: [18]}
  - {name: stool, labels: [19]}
  - {name: towel, labels: [20]}
  - {name: mirror, labels: [21]}
  - {name: tv_monitor, labels: [22]}
  - {name: shower, labels: [23]}
  - {name: column, labels: [24]}
  - {name: bathtub, labels: [25]}
  - {name: counter, labels: [26]}
  - {name: fireplace, labels: [27]}
  - {name: lighting, labels: [28]}
  - {name: beam, labels: [29]}
  - {name: railing, labels: [30]}
  - {name: shelving, labels: [31]}
  - {name: blinds, labels: [32]}
  - {name: gym_equipment, labels: [33]}
  - {name: seating, labels: [34]}
  - {name: board_panel, labels: [35]}
  - {name: furniture, labels: [36]}
  - {name: appliances, labels: [37]}
  - {name: clothes, labels: [38]}
  - {name: objects, labels: [39]}
  - {name: misc, labels: [40]}
specified_colors:
  - {name: void, source: raw_int, color: [0, 0, 0]}
  - {name: wall, source: raw_int, color: [31, 119, 180]}
  - {name: floor, source: raw_int, color: [174, 199, 232]}
  - {name: chair, source: raw_int, color: [255, 127, 14]}
  - {name: door, source: raw_int, color: [255, 187, 120]}
  - {name: table, source: raw_int, color: [44, 160, 44]}
  - {name: picture, source: raw_int, color: [152, 223, 138]}
  - {name: cabinet, source: raw_int, color: [214, 39, 40]}
  - {name: cushion, source: raw_int, color: [255, 152, 150]}
  - {name: window, source: raw_int, color: [148, 103, 189]}
  - {name: sofa, source: raw_int, color: [197, 176, 213]}
  - {name: bed, source: raw_int, color: [140, 86, 75]}
  - {name: curtain, source: raw_int, color: [196, 156, 148]}
  - {name: chest_of_drawers, source: raw_int, color: [227, 119, 194]}
  - {name: plant, source: raw_int, color: [247, 182, 210]}
  - {name: sink, source: raw_int, color: [127, 127, 127]}
  - {name: stairs, source: raw_int, color: [199, 199, 199]}
  - {name: ceiling, source: raw_int, color: [188, 189, 34]}
  - {name: toilet, source: raw_int, color: [219, 219, 141]}
  - {name: stool, source: raw_int, color: [23, 190, 207]}
  - {name: towel, source: raw_int, color: [158, 218, 229]}
  - {name: mirror, source: raw_int, color: [57, 59, 121]}
  - {name: tv_monitor, source: raw_int, color: [82, 84, 163]}
  - {name: shower, source: raw_int, color: [107, 110, 207]}
  - {name: column, source: raw_int, color: [156, 158, 222]}
  - {name: bathtub, source: raw_int, color: [99, 121, 57]}
  - {name: counter, source: raw_int, color: [140, 162, 82]}
  - {name: fireplace, source: raw_int, color: [181, 207, 107]}
  - {name: lighting, source: raw_int, color: [206, 219, 156]}
  - {name: beam, source: raw_int, color: [140, 109, 49]}
  - {name: railing, source: raw_int, color: [189, 158, 57]}
  - {name: shelving, source: raw_int, color: [231, 186, 82]}
  - {name: blinds, source: raw_int, color: [231, 203, 148]}
  - {name: gym_equipment, source: raw_int, color: [132, 60, 57]}
  - {name: seating, source: raw_int, color: [173, 73, 74]}
  - {name: board_panel, source: raw_int, color: [214, 97, 107]}
  - {name: furniture, source: raw_int, color: [231, 150, 156]}
  - {name: appliances, source: raw_int, color: [123, 65, 115]}
  - {name: clothes, source: raw_int, color: [165, 81, 148]}
  - {name: objects, source: raw_int, color: [206, 109, 189]}
  - {name: misc, source: raw_int, color: [222, 158, 214]}
