---
# based on https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Semantic Inference Build and Test
# on: [pull_request]
on: {pull_request: {}, push: {branches: [feature/ci]}}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: sudo apt-get update && sudo apt install pipx
      - name: Lint
        run: pipx install pre-commit && cd ${{github.workspace}} && pre-commit run --all-files
  ros2:
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v4
        with: {path: src/semantic_inference}
      - name: Dependencies
        run: |
          apt update && apt install -y python3-vcstool git
          vcs import src < src/semantic_inference/install/packages.yaml
          rosdep update --rosdistro jazzy && rosdep install --rosdistro jazzy --from-paths src --ignore-src -r -y
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
      - name: Test
        shell: bash
        run: |-
          source /opt/ros/jazzy/setup.bash
          colcon test
